-- Remove all existing brands
-- Note: inventory.brand is a text column without FK constraint, so this is safe.
DELETE FROM public.brands;

-- Insert new brands list from user file
INSERT INTO public.brands (name) VALUES
('AF System'),
('Akifix'),
('AMF'),
('Amstrong'),
('ARD'),
('Atena'),
('Beghelli'),
('Bfire'),
('Celenit'),
('Cipriani'),
('Colorificio Sammarinense / COLSAM'),
('D.B.M. fissaggi'),
('De Walt'),
('Electix'),
('Fassa Bortolo'),
('Fertubi Friuli'),
('Fiorellini'),
('Firerock'),
('Fischer'),
('Friulsider'),
('Global Building'),
('Gyproc'),
('Hilti'),
('Intumex'),
('Isover'),
('Ivas'),
('Kaliflex'),
('Klober'),
('Knauf'),
('Lupato'),
('Masker'),
('Metalstampi'),
('MULTI'),
('Multirock'),
('New Idra'),
('Ninz'),
('Officine Nuove'),
('OWA'),
('Paroc'),
('Polymax'),
('Promat'),
('RockFon'),
('RookWool'),
('Sacop'),
('Serex'),
('Sigma'),
('Siniat'),
('SOUDAL'),
('Stiferite'),
('Supalux'),
('Tecbor'),
('Techonicol'),
('Termit'),
('Tesa'),
('Top Lux'),
('Tytan'),
('Wurth')
ON CONFLICT (name) DO NOTHING;
